[package]
name = "config"
version = "0.1.0"
authors = ["Anton Orlov <ion6431@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dotenv = "0.15.0"
log = "0.4"
